/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Login.module.scss";

export default function Login() {
  return (
    <div className={styles.container}>
      <div className={styles.background}>
        <Head>
          <title>Co-Doutor - Login</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/assets/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
          <link
            href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
            rel="stylesheet"
          />
        </Head>

        <main className={styles.main}>
          <div className={styles.logo}>
            <Image
              src="/assets/logo-big.svg"
              alt="Co-doutor Logo"
              width={187}
              height={217}
            />
          </div>
            <form className={styles.login} action="/login" method="post">
            <label>E-mail</label>
            <input
              type="email"
              placeholder="Digite seu e-mail"
              required
            ></input>
            <label>Senha</label>
            <input
              type="password"
              placeholder="Digite sua senha"
              required
            ></input>
            <button type="submit">Entrar</button>
            </form>
        </main>
      </div>
      <footer className={styles.footer}>
        <a
          href="https://github.com/laurabrosa/health-monitoring"
          target="_blank"
          rel="noreferrer"
        >
          <div className={styles.github}>
            <Image
              src="/assets/github-img.svg"
              alt="Github Logo"
              width={18}
              height={18}
            />
          </div>
          Entenda o projeto
        </a>
      </footer>
    </div>
  );
}
